// ✏️ Modifie ici tes contenus : le reste du site se met à jour tout seul.

export const profile = { name: "Manon Farget", email: "farget.manon@gmail.com", linkedin: "https://www.linkedin.com/in/manon-farget-75baa5333/", github: "https://github.com/mfrgt4", cv: "#", photo: "/images/portrait.png", roles: ["Développeuse web", "UI/UX designer", "Motion lover", "Étudiante MMI"] };
export const nav = [["a-propos", "A propos"], ["boite-a-outils", "Ma boîte à outils"], ["projets", "Projets"], ["parcours", "Parcours"], ["contact", "Contact"]] as const;
export type Skill = { icon: string; title: string; text: string; span?: string };
export const skills: Skill[] = [
{ icon: "⚡", title: "Intégration web", text: "HTML sémantique, CSS moderne, React et TypeScript pour des pages rapides et accessibles.", span: "s2 r2" },
{ icon: "🎨", title: "Design UI/UX", text: "Maquettes Figma, design system, prototypage et tests utilisateurs.", span: "s2" },
{ icon: "🎬", title: "Motion & vidéo", text: "After Effects, Premiere Pro." },
{ icon: "🔎", title: "SEO & contenu", text: "Stratégie éditoriale, référencement." },
{ icon: "🤝", title: "Gestion de projet", text: "Travail en équipe, méthode agile, Git et échanges clairs avec le client.", span: "s2" },
];
export const tools = ["React", "TypeScript", "three.js", "Vite", "Vercel", "HTML5", "CSS3", "JavaScript", "Tailwind", "PHP", "SQL", "Git", "GitHub", "Figma", "Photoshop", "Illustrator", "After Effects", "Premiere Pro", "WordPress", "SEO", "UX Design", "Responsive", "Accessibilité", "Node.js", "Agile", "Notion", "Blender", "API REST"];
export type Media = { type: "image" | "video"; src: string; alt: string; poster?: string };
export type Category = "perso" | "universitaire";
export type Project = { icon: string; title: string; kind: string; text: string; stack: string[]; color: string; href: string; category: Category; type?: string; media?: Media[]; pitch?: string; link?: string; linkLabel?: string; link2?: string; linkLabel2?: string };
export const categories = [["perso", "Projets personnels"], ["universitaire", "Projets universitaires"]] as const;
export const projects: Project[] = [
{ icon: "🎨", title: "Montages", pitch: "Création de Reels Instagram et TikTok sur des films et des séries. L’objectif est de développer mon storytelling et ma compréhension des tendances à travers des visuels. Grâce à l’analyse des statistiques et des tendances, mes contenus ont atteint une large audience.", category: "perso", kind: "Projet perso", text: "Création de montages visuels sur After Effects 2020.", stack: ["After Effects"], color: "#024E32", href: "#", link: "https://www.instagram.com/xxmanclouds/?hl=fr", linkLabel: "Voir mon Instagram", link2: "https://www.tiktok.com/@xxmanclouds?_r=1&_t=ZG-9AOBYnJ3lE9", linkLabel2: "Voir mon TikTok", media: [{ type: "image", src: "/projets/perso-edits.png", alt: "Bannière de mes montages persos" }, { type: "video", src: "/projets/Michaelj_Edit.mp4", alt: "Montage sur Michael Jackson" }, { type: "video", src: "/projets/Hunger-Games_Edit.mp4", alt: "Montage sur Hunger Games" }, { type: "video", src: "/projets/Matrix_Edit2.mp4", alt: "Montage sur Matrix" }, { type: "video", src: "/projets/NaomiLapa_Edit.mp4", alt: "Montage Naomi Lapa" }, { type: "video", src: "/projets/Nami-transitions_Edit.mp4", alt: "Montage sur Nami dans One Piece" }, { type: "video", src: "/projets/Matrix_Edit1.mp4", alt: "Deuxième montage sur Matrix" }, { type: "video", src: "/projets/Daeneris_Edit.mp4", alt: "Montage sur Daenerys" }] },
{ icon: "🕹️", title: "Blog", pitch: "Création d’un blog personnel autour de mes passions. L’objectif est de développer ma créativité et mes compétences en webdesign (HTML, CSS, JavaScript), tout en travaillant la mise en page, l’identité visuelle et l’expérience utilisateur.", category: "perso", kind: "Projet perso", text: "Création d'un blog personnel sur Blogger.", stack: ["Blogger"], color: "#024E32", href: "#", link: "https://thepopstardiary.blogspot.com/", linkLabel: "Voir mon Blog", media: [{ type: "image", src: "/projets/blog.png", alt: "Bannière mon blog" }] },
{ icon: "🌐", title: "Ce portfolio", pitch: "Le site que tu es en train de regarder : React, TypeScript et three.js, avec une sphère 3D interactive, déployé sur Vercel.", category: "perso", kind: "Projet perso", text: "React, TypeScript, sphère 3D, déployé sur Vercel.", stack: ["React", "three.js", "Vercel"], color: "#D13670", href: "#", media: [{ type: "image", src: "/projets/banniere-portfolio.png", alt: "Bannière du portfolio de Manon Farget" }] },
{ icon: "🛒", title: "SAE203 - Concevoir un Site Web avec BDD", pitch: "Création d’un site immersif inspiré de The Vampire Diaries, de la base de données MySQL au développement de l’interface. Réalisation d’un site responsive avec PHP, HTML, CSS et JavaScript, intégrant des filtres interactifs, des animations et un espace administrateur sécurisé.", category: "universitaire", type: "Développement web", kind: "", text: "Site web immersif avec base de données, filtres interactifs et espace administrateur sécurisé.", stack: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"], color: "#D13670", href: "#", link: "https://manon.farget.fr/MysticFalls/", linkLabel: "Découvrir le site", media: [{ type: "image", src: "/projets/Mystic-falls.png", alt: "Aperçu du site immersif Mystic Falls" }] },
{ icon: "📰", title: "SAE102 - IKEA x Animal Crossing", pitch: "Conception de « Le Coin Fruité », une gamme de produits issue d’une collaboration fictive entre IKEA et Animal Crossing. Élaboration d’une stratégie marketing et de communication, avec définition des cibles, des objectifs, de la proposition de valeur et création d’une affiche promotionnelle sur InDesign.", category: "universitaire", type: "Branding & Design", kind: "Projet universitaire", text: "Imagination d’une collaboration entre IKEA et Animal Crossing : « Le Coin Fruité », des meubles inspirés des fruits pour votre intérieur.", stack: ["Stratégie marketing", "Communication", "Conception graphique", "InDesign", "Canva"], color: "#D13670", href: "#", media: [{ type: "image", src: "/projets/Le-Coin-Fruite.jpg", alt: "Affiche promotionnelle de la gamme Le Coin Fruité" }] },
{ icon: "📰", title: "SAE202 - Decathlon Gym, la salle qui vous correspond", pitch: "Création d’une campagne de communication pour Decathlon Gym, un concept de salles de sport éco-conçues et accessibles, incluant une stratégie marketing, une vidéo promotionnelle où j'ai réalisé la prise du son et un site web réalisé avec WordPress.", category: "universitaire", type: "Communication & Marketing", kind: "Projet universitaire", text: "Création d’une campagne de communication pour Decathlon Gym, un concept de salles de sport éco-conçues et accessibles.", stack: ["Stratégie marketing", "Communication", "Création audiovisuelle", "Prise de son", "WordPress", "Figma", "Excel"], color: "#D13670", href: "#", link: "https://decathlongym.sae202.mmilepuy.fr/", linkLabel: "Voir le site", media: [{ type: "image", src: "/projets/Decathlon-Gym.jpg", alt: "Séance de boxe lors d’un entraînement chez Decathlon Gym" }] },
{ icon: "📰", title: "SAE104 - Production d'un tutoriel audio et vidéo", pitch: "Montage d’un tutoriel vidéo de deux minutes scénarisé en anglais. Préparation du storyboard en équipe, puis montage sur Adobe Premiere Pro avec effets visuels, bruitages et sous-titres.", category: "universitaire", type: "Audiovisuel", kind: "Projet universitaire", text: "Réalisation d’un tutoriel vidéo de deux minutes en anglais, avec montage dynamique, effets visuels, bruitages et sous-titres.", stack: ["Montage vidéo", "Adobe Premiere Pro", "Effets visuels", "Sound design", "Sous-titrage", "Scénarisation"], color: "#D13670", href: "#", media: [{ type: "image", src: "/projets/Mojito.png", alt: "Visuel promotionnel du tuto Mojito" }] },
];

export function projectUrl(project: Project): string {
  return project.link || project.href || "#";
}

export const studies = [
{ when: "2025 — 2027", title: "BUT MMI — Métiers du Multimédia et de l'Internet", text: "Université Clermont Auvergne · IUT du Puy-en-Velay. Parcours : à compléter." },
{ when: "2022 — 2025", title: "Baccalauréat", text: "Série / spécialités : à compléter · Lycée : à compléter." },
{ when: "Avril 2027", title: "Stage recherché", text: "Prochaine étape : une équipe qui me fera progresser.", accent: true },
];
export const about = [
"Je m'appelle Manon et je suis étudiante en 2e année de BUT MMI à l'Université Clermont Auvergne, au Puy-en-Velay.",
"J'aime autant coder une interface que la dessiner ou lui donner vie avec du mouvement : développement web, UI/UX design et motion design sont mes terrains de jeu.",
"Je cherche un stage à partir d'avril 2027 pour progresser au sein d'une équipe, et y apporter ma curiosité et mon sens du détail.",
];
export const facts = ["📍 Le Puy-en-Velay", "🎓 BUT MMI · 2e année", "🗓️ Stage avril 2027"];

